### PR TITLE
[MPOM-209] correct jira component url.

### PR DESCRIPTION
**Pull request by ofarganc**
The Jira URL with the component Id was not valid id so  changed it to
https://issues.apache.org/jira/issues/?jql=project%20%3D%20MPOM%20AND%20component%20%3D%20asf

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by hboutemy** [comment]
yes, Jira dropped support for the link to components... :(
can we take a little time to find more readible urls: such urls are really ugly, and since we'll have to do this job for many many Maven components, this won't be lost time!!!
what about https://issues.apache.org/jira/issues/?jql=project%3DMPOM+AND+component%3Dasf ?

then please squash

**Comment by hboutemy** [comment]
I even tried https://issues.apache.org/jira/issues/?jql=project=MPOM+AND+component=asf and it worked in my web browser
 should we keep strict https://issues.apache.org/jira/issues/?jql=project%3DMPOM+AND+component%3Dasf (we removed optional spaces and replaced %20 with +, which is perfectly valid)?
or take the tweak to replace %3D with =, which is AFAIK a little tweak?

**Comment by hboutemy** [comment]
notice, this Git repository is an old svn2git mirror: please open a PR to https://github.com/apache/maven-apache-parent/ instead

**Comment by ofarganc** [comment]
Thanks for the comments @hboutemy . I created another PR from the other repo: https://github.com/apache/maven-apache-parent/pull/3
Therefore closing this one.

**Pull request closed without merging**
